In [30]:
#imports
import pandas as pd
import numpy as np
import networkx as nx
import scipy as sp


In [26]:
#load files
astroph_df = pd.read_csv("communities/CA-AstroPh.txt", skiprows=1,header=None, sep= " ")
condmat_df = pd.read_csv("communities/CA-CondMat.txt", skiprows=1,header=None, sep= " ")
grqc_df = pd.read_csv("communities/CA-GrQc.txt", skiprows=1,header=None, sep= " ")
hepph_df = pd.read_csv("communities/CA-HepPh.txt", skiprows=1,header=None, sep= " ")
hepth_df = pd.read_csv("communities/CA-HepTh.txt", skiprows=1,header=None, sep= " ")

In [152]:
astroph_df.shape
#condmat_df.head()
#grqc_df.head()
#hepph_df.head()
#hepth_df.head()

# ca-AstroPh 17903 197031 50
# ca-CondMat 21363 91342 100
# ca-GrQc 4158 13428 2
# ca-HepPh 11204 117649 25
# ca-HepTh 8638 24827 20

(197031, 2)

In [80]:
#vertex_from = astroph_df.loc[:,[0]]
#vertex_from
#node_to = = astroph_df.loc[:,[1]]
astroph_values=astroph_df.values

In [81]:
#create graph
G=nx.Graph()

g = G.add_edges_from(astroph_values)

In [83]:
#create adjecy matrix of graph
A = nx.adjacency_matrix(G)

In [91]:
#create diagonal matrix of graph
#degrees = [val for (node, val) in G.degree()]

In [92]:
degrees

[43,
 51,
 25,
 25,
 33,
 25,
 51,
 51,
 29,
 25,
 25,
 51,
 36,
 38,
 39,
 39,
 37,
 25,
 25,
 25,
 25,
 25,
 82,
 25,
 29,
 32,
 25,
 48,
 25,
 62,
 39,
 31,
 46,
 38,
 44,
 46,
 25,
 25,
 32,
 31,
 43,
 31,
 46,
 25,
 9,
 3,
 2,
 28,
 12,
 9,
 15,
 13,
 4,
 32,
 5,
 6,
 54,
 7,
 120,
 42,
 27,
 48,
 101,
 50,
 10,
 3,
 110,
 22,
 44,
 34,
 233,
 27,
 82,
 2,
 185,
 80,
 29,
 11,
 13,
 38,
 42,
 166,
 41,
 110,
 132,
 15,
 26,
 28,
 7,
 106,
 17,
 172,
 142,
 145,
 124,
 21,
 4,
 15,
 3,
 3,
 36,
 15,
 88,
 19,
 15,
 15,
 15,
 14,
 15,
 15,
 26,
 23,
 15,
 15,
 19,
 33,
 15,
 62,
 11,
 16,
 9,
 16,
 19,
 66,
 10,
 28,
 7,
 8,
 18,
 39,
 8,
 37,
 11,
 11,
 16,
 19,
 16,
 78,
 6,
 19,
 11,
 10,
 25,
 113,
 6,
 17,
 19,
 39,
 8,
 17,
 144,
 11,
 14,
 8,
 11,
 65,
 11,
 42,
 8,
 6,
 7,
 47,
 9,
 36,
 34,
 8,
 96,
 85,
 7,
 37,
 8,
 8,
 26,
 31,
 27,
 4,
 26,
 34,
 20,
 12,
 12,
 3,
 6,
 15,
 1,
 13,
 4,
 19,
 18,
 32,
 80,
 32,
 108,
 48,
 17,
 38,
 18,
 35,
 38,
 40,
 36,
 40,
 35,
 46,

In [107]:
#calculate laplacian
laplacian_astroph = nx.normalized_laplacian_matrix(G)

In [110]:
laplacian_astroph

<17903x17903 sparse matrix of type '<class 'numpy.float64'>'
	with 411847 stored elements in Compressed Sparse Row format>

In [111]:
laplacian_astroph = sp.sparse.identity(17903).toarray() - laplacian_astroph

In [112]:
#laplacian_astroph = laplacian_astroph.asfptype()

AttributeError: 'matrix' object has no attribute 'asfptype'

In [113]:
laplacian_astroph

matrix([[  0.00000000e+00,   2.13540711e-02,   3.04997141e-02, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  2.13540711e-02,   1.11022302e-16,   2.80056017e-02, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  3.04997141e-02,   2.80056017e-02,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        ..., 
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   2.22044605e-16]])

In [174]:
#eigenvectors
#nxk
amount = 10
eig_val, u = sp.sparse.linalg.eigs(laplacian_astroph, k=amount)

In [175]:
 u

array([[  1.04468285e-02+0.j,  -2.02244585e-04+0.j,   1.81558355e-04+0.j,
        ...,   3.72772583e-03+0.j,   6.36739284e-04+0.j,
         -1.71328748e-03+0.j],
       [  1.13771982e-02+0.j,  -2.19146719e-04+0.j,   2.05414761e-04+0.j,
        ...,   3.83771745e-03+0.j,   6.74064271e-04+0.j,
         -1.78536806e-03+0.j],
       [  7.96563202e-03+0.j,  -1.53654694e-04+0.j,   1.39757650e-04+0.j,
        ...,   2.76994420e-03+0.j,   4.71962061e-04+0.j,
         -1.25798655e-03+0.j],
       ..., 
       [  1.59312640e-03+0.j,  -2.66235107e-05+0.j,   4.83086057e-05+0.j,
        ...,  -5.86453286e-05+0.j,   2.45295723e-05+0.j,
         -1.35286340e-05+0.j],
       [  1.59312640e-03+0.j,  -2.74808543e-05+0.j,   5.00275541e-05+0.j,
        ...,  -5.64991935e-05+0.j,  -4.43972954e-05+0.j,
          1.19915644e-03+0.j],
       [  2.25302097e-03+0.j,  -3.73933304e-05+0.j,   6.79849397e-05+0.j,
        ...,  -8.48788624e-05+0.j,   4.11164388e-05+0.j,
         -3.01047868e-05+0.j]])

In [176]:
u_norm = sp.linalg.norm(u, axis=1, ord=1)

In [177]:
u_norm

array([ 0.02025407,  0.02162771,  0.01524701, ...,  0.00205409,
        0.00324232,  0.00288666])

In [178]:
#normalized_u = u / u_norm[:, None] or None is newaxis
normalized_u = u / u_norm[:,np.newaxis]

In [179]:
normalized_u

array([[ 0.51578919+0.j, -0.00998538+0.j,  0.00896404+0.j, ...,
         0.18404827+0.j,  0.03143760+0.j, -0.08458980+0.j],
       [ 0.52604736+0.j, -0.01013268+0.j,  0.00949776+0.j, ...,
         0.17744449+0.j,  0.03116670+0.j, -0.08255004+0.j],
       [ 0.52243893+0.j, -0.01007769+0.j,  0.00916623+0.j, ...,
         0.18167130+0.j,  0.03095440+0.j, -0.08250709+0.j],
       ..., 
       [ 0.77558637+0.j, -0.01296120+0.j,  0.02351822+0.j, ...,
        -0.02855048+0.j,  0.01194180+0.j, -0.00658618+0.j],
       [ 0.49135451+0.j, -0.00847569+0.j,  0.01542958+0.j, ...,
        -0.01742557+0.j, -0.01369308+0.j,  0.36984569+0.j],
       [ 0.78049283+0.j, -0.01295382+0.j,  0.02355138+0.j, ...,
        -0.02940378+0.j,  0.01424358+0.j, -0.01042892+0.j]])

In [181]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10, random_state=0).fit(normalized_u)




In [184]:
kmeans.labels_[0:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5,
       5, 5, 5, 5, 5, 8, 5, 5, 0, 0, 5, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

In [183]:
vertex_id = np.arange(17903)
cluster_id = kmeans.labels_
concat_arr = np.column_stack((vertex_id, cluster_id))

#concat_arr[0:5]
concat_df = pd.DataFrame({'vertex_id':concat_arr[:,1],'cluster_id':concat_arr[:,0]})

concat_df

cluster_id  vertex_id
0               0          0
1               1          0
2               2          0
3               3          0
4               4          0
5               5          0
6               6          0
7               7          0
8               8          0
9               9          0
10             10          0
11             11          0
12             12          0
13             13          0
14             14          0
15             15          0
16             16          0
17             17          0
18             18          0
19             19          0
20             20          0
21             21          0
22             22          0
23             23          0
24             24          0
25             25          0
26             26          0
27             27          0
28             28          0
29             29          0
...           ...        ...
17873       17873          5
17874       17874          5
17875       17875          5
17876       17876          5
17877       17877          0
17878       17878          5
17879       17879          5
17880       17880          5
17881       17881          5
17882       17882          5
17883       17883          5
17884       17884          5
17885       17885          5
17886       17886          5
17887       17887          0
17888       17888          5
17889       17889          5
17890       17890          5
17891       17891          5
17892       17892          5
17893       17893          5
17894       17894          5
17895       17895          5
17896       17896          0
17897       17897          5
17898       17898          5
17899       17899          5
17900       17900          5
17901       17901          3
17902       17902          5

[17903 rows x 2 columns]

In [187]:
concat_df.to_csv("CA-AstroPh.csv", sep='\t', index=False)

In [74]:


#vertex_from = astroph_df.loc[:,[0]].values.flatten()
#node_to = astroph_df.loc[:,[1]].values.flatten()
#node_to.values.max
#vertex_from.size

#node_to.values.max()
#vertex_from
#edge_u = np.array([0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4])
#edge_u.shape
#node_to.shape
#edge_u.shape()
# astro_adj = adjacency_matrix(vertex_from, node_to,17903)