In [1]:
#imports
import pandas as pd
import numpy as np
import networkx as nx
import scipy as sp
from sklearn.cluster import KMeans

In [2]:
#load files
astroph_df = pd.read_csv("communities/CA-AstroPh.txt", skiprows=1,header=None, sep= " ")
condmat_df = pd.read_csv("communities/CA-CondMat.txt", skiprows=1,header=None, sep= " ")
grqc_df = pd.read_csv("communities/CA-GrQc.txt", skiprows=1,header=None, sep= " ")
hepph_df = pd.read_csv("communities/CA-HepPh.txt", skiprows=1,header=None, sep= " ")
hepth_df = pd.read_csv("communities/CA-HepTh.txt", skiprows=1,header=None, sep= " ")

In [31]:
astroph_df.shape[1]
#condmat_df.head()
#grqc_df.head()
#hepph_df.head()
#hepth_df.head()

# ca-AstroPh 17903 197031 50
# ca-CondMat 21363 91342 100
# ca-GrQc 4158 13428 2
# ca-HepPh 11204 117649 25
# ca-HepTh 8638 24827 20

2

In [4]:
#vertex_from = astroph_df.loc[:,[0]]
#vertex_from
#node_to = = astroph_df.loc[:,[1]]
astroph_values=astroph_df.values

In [5]:
#create graph
G=nx.Graph()

g = G.add_edges_from(astroph_values)

In [83]:
#create adjecy matrix of graph
A = nx.adjacency_matrix(G)

In [91]:
#create diagonal matrix of graph
#degrees = [val for (node, val) in G.degree()]

In [92]:
degrees

[43,
 51,
 25,
 25,
 33,
 25,
 51,
 51,
 29,
 25,
 25,
 51,
 36,
 38,
 39,
 39,
 37,
 25,
 25,
 25,
 25,
 25,
 82,
 25,
 29,
 32,
 25,
 48,
 25,
 62,
 39,
 31,
 46,
 38,
 44,
 46,
 25,
 25,
 32,
 31,
 43,
 31,
 46,
 25,
 9,
 3,
 2,
 28,
 12,
 9,
 15,
 13,
 4,
 32,
 5,
 6,
 54,
 7,
 120,
 42,
 27,
 48,
 101,
 50,
 10,
 3,
 110,
 22,
 44,
 34,
 233,
 27,
 82,
 2,
 185,
 80,
 29,
 11,
 13,
 38,
 42,
 166,
 41,
 110,
 132,
 15,
 26,
 28,
 7,
 106,
 17,
 172,
 142,
 145,
 124,
 21,
 4,
 15,
 3,
 3,
 36,
 15,
 88,
 19,
 15,
 15,
 15,
 14,
 15,
 15,
 26,
 23,
 15,
 15,
 19,
 33,
 15,
 62,
 11,
 16,
 9,
 16,
 19,
 66,
 10,
 28,
 7,
 8,
 18,
 39,
 8,
 37,
 11,
 11,
 16,
 19,
 16,
 78,
 6,
 19,
 11,
 10,
 25,
 113,
 6,
 17,
 19,
 39,
 8,
 17,
 144,
 11,
 14,
 8,
 11,
 65,
 11,
 42,
 8,
 6,
 7,
 47,
 9,
 36,
 34,
 8,
 96,
 85,
 7,
 37,
 8,
 8,
 26,
 31,
 27,
 4,
 26,
 34,
 20,
 12,
 12,
 3,
 6,
 15,
 1,
 13,
 4,
 19,
 18,
 32,
 80,
 32,
 108,
 48,
 17,
 38,
 18,
 35,
 38,
 40,
 36,
 40,
 35,
 46,

In [17]:
#calculate laplacian
laplacian_astroph = nx.normalized_laplacian_matrix(G)

In [32]:
laplacian_astroph.shape

(17903, 17903)

In [19]:
laplacian_astroph_notsparse = sp.sparse.identity(17903).toarray() - laplacian_astroph
laplacian_astroph_normalized = sp.sparse.csr_matrix(laplacian_astroph_notsparse)

In [112]:
#laplacian_astroph = laplacian_astroph.asfptype()

AttributeError: 'matrix' object has no attribute 'asfptype'

In [20]:
laplacian_astroph_normalized

<17903x17903 sparse matrix of type '<class 'numpy.float64'>'
	with 403824 stored elements in Compressed Sparse Row format>

In [21]:
#eigenvectors
#nxk
amount = 50
eig_val, u = sp.sparse.linalg.eigs(laplacian_astroph_normalized, k=amount)

In [22]:
 u

array([[ -1.04468285e-02+0.j,  -2.02244585e-04+0.j,   1.81558355e-04+0.j,
        ...,  -3.14498489e-03+0.j,   3.79705635e-04+0.j,
         -4.67615560e-04+0.j],
       [ -1.13771982e-02+0.j,  -2.19146719e-04+0.j,   2.05414761e-04+0.j,
        ...,  -3.11735375e-03+0.j,   4.92818017e-04+0.j,
         -4.45320229e-04+0.j],
       [ -7.96563202e-03+0.j,  -1.53654694e-04+0.j,   1.39757650e-04+0.j,
        ...,  -2.25490590e-03+0.j,   2.98023048e-04+0.j,
         -3.25969168e-04+0.j],
       ..., 
       [ -1.59312640e-03+0.j,  -2.66235107e-05+0.j,   4.83086057e-05+0.j,
        ...,  -2.43017463e-05+0.j,  -4.25808242e-05+0.j,
         -1.51605184e-05+0.j],
       [ -1.59312640e-03+0.j,  -2.74808543e-05+0.j,   5.00275541e-05+0.j,
        ...,  -4.39480147e-05+0.j,   1.39830239e-05+0.j,
          4.00802379e-05+0.j],
       [ -2.25302097e-03+0.j,  -3.73933304e-05+0.j,   6.79849397e-05+0.j,
        ...,  -2.11732566e-05+0.j,  -5.54420275e-05+0.j,
         -2.28959342e-05+0.j]])

In [23]:
u_norm = sp.linalg.norm(u, axis=1, ord=1)

In [24]:
u_norm

array([ 0.39955371,  0.41338155,  0.29221132, ...,  0.00383468,
        0.00578134,  0.00535619])

In [25]:
#normalized_u = u / u_norm[:, None] or None is newaxis
normalized_u = u / u_norm[:,np.newaxis]

In [26]:
normalized_u

array([[-0.02614624+0.j, -0.00050618+0.j,  0.00045440+0.j, ...,
        -0.00787124+0.j,  0.00095032+0.j, -0.00117034+0.j],
       [-0.02752227+0.j, -0.00053013+0.j,  0.00049691+0.j, ...,
        -0.00754111+0.j,  0.00119216+0.j, -0.00107726+0.j],
       [-0.02725983+0.j, -0.00052583+0.j,  0.00047828+0.j, ...,
        -0.00771670+0.j,  0.00101989+0.j, -0.00111553+0.j],
       ..., 
       [-0.41545241+0.j, -0.00694283+0.j,  0.01259782+0.j, ...,
        -0.00633736+0.j, -0.01110414+0.j, -0.00395353+0.j],
       [-0.27556368+0.j, -0.00475337+0.j,  0.00865329+0.j, ...,
        -0.00760170+0.j,  0.00241865+0.j,  0.00693269+0.j],
       [-0.42063884+0.j, -0.00698133+0.j,  0.01269278+0.j, ...,
        -0.00395305+0.j, -0.01035102+0.j, -0.00427467+0.j]])

In [27]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=50, random_state=0).fit(normalized_u)




In [28]:
kmeans.labels_[0:100]

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 19, 19, 19,  8, 19, 48,  8,
       19,  8, 45,  4,  4, 36,  4,  4,  4, 45, 45, 45, 45, 45, 45, 45, 45,
       45,  8, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45,
       45, 45, 45, 45, 45, 45, 45, 45, 45, 45,  0,  8,  0,  0,  0])

In [63]:
vertex_id = np.arange(17903)
cluster_id = kmeans.labels_
concat_arr = np.column_stack((vertex_id, cluster_id))

#concat_arr[0:5]
concat_df = pd.DataFrame({'vertex_id':concat_arr[:,1],'cluster_id':concat_arr[:,0]})

concat_df

cluster_id  vertex_id
0               0         17
1               1         17
2               2         17
3               3         17
4               4         17
5               5         17
6               6         17
7               7         17
8               8         17
9               9         17
10             10         17
11             11         17
12             12         17
13             13         17
14             14         17
15             15         17
16             16         17
17             17         17
18             18         17
19             19         17
20             20         17
21             21         17
22             22         17
23             23         17
24             24         17
25             25         17
26             26         17
27             27         17
28             28         17
29             29         17
...           ...        ...
17873       17873         45
17874       17874         19
17875       17875          8
17876       17876          8
17877       17877         44
17878       17878         38
17879       17879          8
17880       17880          8
17881       17881         38
17882       17882          8
17883       17883         19
17884       17884         19
17885       17885          3
17886       17886          0
17887       17887         11
17888       17888         45
17889       17889         45
17890       17890         19
17891       17891          0
17892       17892          8
17893       17893         45
17894       17894          8
17895       17895          8
17896       17896          4
17897       17897         45
17898       17898          8
17899       17899          8
17900       17900         45
17901       17901          0
17902       17902         45

[17903 rows x 2 columns]

In [66]:
concat_arr_df = pd.DataFrame(concat_arr)



concat_arr_df.to_csv("test.csv", sep=' ', index=False, header=False)

In [65]:
concat_arr_df

0   1
0          0  17
1          1  17
2          2  17
3          3  17
4          4  17
5          5  17
6          6  17
7          7  17
8          8  17
9          9  17
10        10  17
11        11  17
12        12  17
13        13  17
14        14  17
15        15  17
16        16  17
17        17  17
18        18  17
19        19  17
20        20  17
21        21  17
22        22  17
23        23  17
24        24  17
25        25  17
26        26  17
27        27  17
28        28  17
29        29  17
...      ...  ..
17873  17873  45
17874  17874  19
17875  17875   8
17876  17876   8
17877  17877  44
17878  17878  38
17879  17879   8
17880  17880   8
17881  17881  38
17882  17882   8
17883  17883  19
17884  17884  19
17885  17885   3
17886  17886   0
17887  17887  11
17888  17888  45
17889  17889  45
17890  17890  19
17891  17891   0
17892  17892   8
17893  17893  45
17894  17894   8
17895  17895   8
17896  17896   4
17897  17897  45
17898  17898   8
17899  17899   8
17900  17900  45
17901  17901   0
17902  17902  45

[17903 rows x 2 columns]

In [67]:
def line_prepender(filename, line):
    with open(filename, 'r+') as f:
        content = f.read()
        f.seek(0, 0)
        f.write(line.rstrip('\r\n') + '\n' + content)
        
line_prepender("test.csv", "# dsads dsad sdsd")        
        

In [196]:
concat_df.to_csv("CA-AstroPh.csv", sep='\t', index=False)

In [70]:
def normalized_spectral_clustering(vertices, k_eigval):
    
    G=nx.Graph()
    g = G.add_edges_from(vertices)
    
    #calculate laplacian
    laplacian = nx.normalized_laplacian_matrix(G)
    #normalize laplicacian
    laplacian_normalized = sp.sparse.identity(laplacian.shape[0]).toarray() - laplacian_astroph
    laplacian_normalized = sp.sparse.csr_matrix(laplacian_normalized)
    
    #calcluate k eigenvectors and form matrix U
    eig_val, U = sp.sparse.linalg.eigs(laplacian_astroph_normalized, k=k_eigval)
    
    #normalize U rows to have 1 norm
    u_norm = sp.linalg.norm(U, axis=1, ord=1)
    u_normalized = U / u_norm[:,np.newaxis]
    
    #cluster the U points to k clusters
    kmeans = KMeans(n_clusters=k_eigval, random_state=0).fit(u_normalized)
    
    vertex_id = np.arange(laplacian.shape[0])
    cluster_id = kmeans.labels_
    concat_arr = np.column_stack((vertex_id, cluster_id))
    
    #concat_df = pd.DataFrame({'vertex_id':concat_arr[:,1],'cluster_id':concat_arr[:,0]})
    return concat_arr
    
    
def write_to_csv(clustering, name, header):
    concat_arr_df = pd.DataFrame(concat_arr)
    concat_arr_df.to_csv(name, sep=' ', index=False, header=False)
    
    def line_prepender(filename, line):
        with open(filename, 'r+') as f:
            content = f.read()
            f.seek(0, 0)
            f.write(line.rstrip('\r\n') + '\n' + content)
            
    line_prepender(name, header)   
    
    

#'# ca-AstroPh 17903 197031 50'

In [69]:
re = normalized_spectral_clustering(astroph_values, 50)
re

array([[    0,    17],
       [    1,    17],
       [    2,    17],
       ..., 
       [17900,    45],
       [17901,     0],
       [17902,    45]])

In [71]:
write_to_csv(re, 'CA-AstroPh.csv', '# ca-AstroPh 17903 197031 50')